services:
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password123
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    env_file:
      - ./.env